# -*- coding: utf-8 -*-
"""Daeguro_Hackathon_Gaussian.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-kXIjOwFORYMmC1HQ20bUGfUQVsENOi4
"""

from sklearn.datasets import load_iris
from sklearn.cluster import KMeans
from sklearn.mixture import GaussianMixture
import pandas as pd

df = pd.read_csv('/content/sample_data/(Final)yayaya4.csv')

print(df)

#MinMaxScaler 적용(표준화)
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

scaler.fit(df)
df_scaled = scaler.transform(df)
df_scaled
df_scaled = pd.DataFrame(df_scaled, columns = ['2030대 인구', '유동인구','대구로카페주문고객'])

df_scaled['총점'] = df_scaled['2030대 인구'] + df_scaled['유동인구']+ df_scaled['대구로카페주문고객']
df_scaled


gmm = GaussianMixture(n_components=3, random_state=0).fit(df_scaled)
gmm
gmm_cluster_labels = gmm.predict(df_scaled)

df_scaled['gmm_cluster'] = gmm_cluster_labels
print(df_scaled)

df_scaled.to_csv('/content/sample_data/Gaussian_result.csv')